/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ElectionManager } from "./ElectionManager";
export * as factories from "./factories";
export { ElectionManager__factory } from "./factories/ElectionManager__factory";
